### ISSUE TITLE
Issue with Arducam SKU: B0444 on Raspberry Pi 5 after installing python3-picamera2

### ISSUE THREAD

**Issue by AraKiLiu** [ArduCAM/Arducam-Pivariety-V4L2-Driver#52]
I am using an Arducam camera with the following details:

\* **SKU:** B0444

\* **Features:** Wide Angle Ultra Low Light

\* **Pin/Connect Type:** 22/TOP

I am encountering issues when trying to use this camera on my Raspberry Pi 5. Below is the current state of my system:

```bash
pi@raspberrypi:~ $ dpkg -l | grep libcamera

ii  libcamera-dev:arm64                  0.3.1+rpt20240909-1                 arm64        complex camera support library (development files)

ii  libcamera-ipa:arm64                  0.3.1+rpt20240909-1                 arm64        complex camera support library (IPA modules)

ii  libcamera0.3:arm64                   0.3.1+rpt20240909-1                 arm64        complex camera support library

ii  pipewire-libcamera:arm64             0.3.65-3+rpt9+deb12u1               arm64        PipeWire libcamera plugin

pi@raspberrypi:~ $ libcamera-hello --list-cameras

Available cameras

\-----------------

0 : arducam-pivariety [1920x1080 10-bit RGGB] (/base/axi/pcie@120000/rp1/i2c@80000/arducam_pivariety@c)

​    Modes: 'SRGGB10_CSI2P' : 1920x1080 [60.00 fps - (65535, 65535)/65535x65535 crop]
```

However, when I attempt to initialize Picamera2 in Python, I get the following error:

```bash
pi@raspberrypi:~ $ python -c "from picamera2 import Picamera2;picam2 = Picamera2();"

Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'picamera2'
```

The issue started after running the following command:

```bash
pi@raspberrypi:~ $ sudo apt install -y python3-picamera2
```

Upon installing `python3-picamera2`, `libcamera` was updated and now the camera is no longer detected. Running `libcamera-hello --list-cameras` returns "No cameras available."

```bash
pi@raspberrypi:~ $ dpkg -l | grep libcamera

ii  libcamera-dev:arm64                  0.3.2+rpt20240927-1                 arm64        complex camera support library (development files)

ii  libcamera-ipa:arm64                  0.3.2+rpt20240927-1                 arm64        complex camera support library (IPA modules)

ii  libcamera0.3:arm64                   0.3.2+rpt20240927-1                 arm64        complex camera support library

ii  python3-libcamera:arm64              0.3.2+rpt20240927-1                 arm64        complex camera support library (Python bindings)
```

When I try to initialize Picamera2 after the update, I get the following error messages:

```bash
[0:17:31.299846939] [5438]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b

[0:17:31.307369198] [5441]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:33:32)

[0:17:31.321947807] [5441]  WARN CameraSensorProperties camera_sensor_properties.cpp:305 No static properties available for 'arducam-pivariety'

[0:17:31.321965085] [5441]  WARN CameraSensorProperties camera_sensor_properties.cpp:307 Please consider updating the camera sensor properties database

[0:17:31.323534858] [5441] ERROR IPAProxy ipa_proxy.cpp:154 Configuration file 'arducam-pivariety.json' not found for IPA module 'rpi/pisp'

[0:17:31.328153267] [5441] ERROR IPARPI ipa_base.cpp:127 Could not create camera helper for arducam-pivariety

[0:17:31.328165156] [5441] ERROR RPI pipeline_base.cpp:820 Failed to load a suitable IPA library

[0:17:31.328171175] [5441] ERROR RPI pisp.cpp:922 Failed to register camera arducam-pivariety 4-000c: -22
```

Additionally, the following traceback is shown:

```bash
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 257, in __init__

​    camera_num = self.global_camera_info()[camera_num]['Num']

​                 \~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^

IndexError: list index out of range
```

I am looking for advice on how to resolve this issue. I suspect it might be related to the version of `libcamera` or missing configuration files for Arducam. Any suggestions or insights would be greatly appreciated.

**Comment by flipphillips** [comment]
I have a similar question about "IPAProxy ipa_proxy.cpp:154 Configuration file 'arducam-pivariety.json' "

That is a 'generic' sort of configuration name, not associated with the 0444 / so I'm guessing one needs to hand-wire one to get that message to go away.
